name: CI/CD Pipeline for HTML/CSS

on: [push]  # Trigger the pipeline on code pushes

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux-based runner

    steps:
      #- uses: actions/checkout@v3  # Checkout the code
      #- name: Install dependencies (if any)
       # run: npm install  # Example for installing npm packages
      #- name: Lint HTML and CSS (optional)
       # run: npm run lint  # Example for running linting tools
      #- name: Run basic tests (optional)
      #  run: npm test  # Example for running simple tests like broken link checks
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Store hostname or IP in a secret
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  # Use an SSH key for authentication
          script: |
            cd /var/www/html  #Adjust path to your web root
            sudo rm -rf *  # Optional: Delete existing files (use with caution)
            scp -r sat-project .  # Replace with actual source directory
            sudo systemctl restart apache2  # Restart Apache to apply changes
